gps2utm:
  ros__parameters:
    position_topic: /nav/sensors/subsonus_usbl/fix
    topics: []
    projected_frame: utm_local
    map_projection: utm
    utm_zone: 19
    origin_lat: 43.61214232381858     # Replace with your local datum origin latitude
    origin_lon: -76.55326599612673   # Replace with your local datum origin longitude
    origin_z: 0.0            # Often 0, or you can use seafloor depth reference
