/**:
  ros__parameters:
    base_frame: base_link
    map_frame: map
    odom_frame: odom
    odom_topic: odom
    sensor_timeout: 2.0
    sensors:
      subsonus_usbl:
        topics:
          orientation: sensors/subsonus_usbl/ins/imu
          position: sensors/subsonus_usbl/ins/fix
          velocity: sensors/subsonus_usbl/ins/twist
    sensors_names:
    - subsonus_usbl
    use_sim_time: false